<?php
/**
 * 详单与 API模块下的公共 控制机  如果不需要登录场景继承我们这个控制器
 * 如果需要登录场景 那他需要继承AuthBase
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/7/1
 * Time: 20:26
 */

namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase  extends BaseController
{
   public  function  initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
   }
   public function  show(...$args){
        throw new HttpResponseException(show(...$args));
   }
}