<?php
/**
 *
 * 是需要登录的时候继承
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/7/1
 * Time: 20:28
 */

namespace app\api\controller;




class AuthBase  extends  ApiBase
{
    public  $userId =0;
    public  $username ="";
    public  $accessToken = "";
    public  $isLogin = 1;

    public  function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if($this->isLogin == 1){
            $this->userId = 20;//测试场景
            return true;
        }
        $this->accessToken = $this->request->header("access_token");
        if(!$this->accessToken || !$this->isLogin()){
            return $this->show(config("status.not_login"),"没有登录");
        }

    }

    /*
     *判断前台用户是否登录
     * @return bool
     */
      public function isLogin(){
       $userInfo = cache(config("redis.token_pre").$this->accessToken);
          if(!$userInfo){
              return false;
          }
          if(!empty($userInfo['id']) && !empty($userInfo['username'])){
              $this->username = $userInfo['username'];
              $this->userId= $userInfo['id'];
              return true;
          }
          return false;
      }



}